[build]
  publish = "public/"
  command = "yarn run netlify:build"
[build.environment]
	CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
	TERM = "xterm"
[[plugins]]
  package = "@netlify/plugin-gatsby"
[[plugins]]
	package = "netlify-plugin-cypress"
