export const headerFont: string;
export const bodyFont: string;
export const hero: string;
export const mainTitle: string;
export const subTitle: string;
export const retailers: string;
export const availableText: string;
export const arrow: string;
export const arrowdown: string;
