export const header: string;
export const menuButton: string;
export const menuBars: string;
export const menuText: string;
export const menuTextClose: string;
export const overlayNavigation: string;
export const menuInput: string;
export const menuTextOpen: string;
export const nav: string;
