export const headerFont: string;
export const bodyFont: string;
export const letterSpacing: string;
export const cardWidth: string;
export const navLinkContainer: string;
export const navLink: string;
export const menuup: string;
export const navSubHeader: string;
export const navHeader: string;
