backend:
    name: git-gateway
    branch: master

# TODO set these options more carefully (uploads folder)
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
    - name: miscellany
      label: Miscellany
      folder: content/miscellany
      create: true
      slug: index
      media_folder: ''
      public_folder: ''
      path: '{{title}}/index'
      editor:
          preview: false
      fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Subtitle
            name: subtitle
            widget: string
            required: false
          - label: Publish Date
            name: date
            widget: datetime
            required: true
          - label: SEO Description
            name: description
            widget: string
            required: false
          - label: Post Image
            name: featuredImage
            widget: image
            required: true
          - label: Body
            name: body
            widget: markdown
            required: true
    - name: chronology
      label: Chronology
      folder: content/chronology
      create: true
      slug: index
      media_folder: ''
      public_folder: ''
      path: '{{title}}/index'
      editor:
          preview: false
      fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: SEO Description
            name: description
            widget: string
            required: false
          - label: Featured Image
            name: featuredImage
            widget: image
            required: false
          - label: Timeline Date
            name: timelineDate
            widget: datetime
            required: true
            time_format: false
            date_format: true
          - label: Display Date
            name: displayDate
            widget: string
            required: true
          - label: Type of Content
            name: category
            widget: select
            required: true
            default: 'events'
            options:
                - { label: 'Family', value: 'family' }
                - { label: 'Colleagues', value: 'colleagues' }
                - { label: 'Events', value: 'events' }
          - label: Card Content
            name: card
            widget: markdown
            required: true
          - label: Article Content
            name: body
            widget: markdown
            required: false
    - name: contenders
      label: Contenders
      folder: content/contenders
      create: true
      slug: index
      media_folder: ''
      public_folder: ''
      path: '{{title}}/index'
      editor:
          preview: false
      fields:
          - label: Name
            name: title
            widget: string
            required: true
          - label: SEO Description
            name: description
            widget: string
            required: false
          - label: Featured Image
            name: featuredImage
            widget: image
            required: true
          - label: Term Start Date
            name: date
            widget: datetime
            required: true
            time_format: false
            date_format: true
          - label: Display Date
            name: displayDate
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            required: false
    - name: pages
      label: Pages and Content
			files:
				- label: "Front page"
      folder: content/pages
      create: true
      slug: index
      media_folder: ''
      public_folder: ''
      path: '{{title}}/index'
      editor:
          preview: false
      fields:
          - label: Name
            name: title
            widget: string
            required: true
          - label: SEO Description
            name: description
            widget: string
            required: false
          - label: Featured Image
            name: featuredImage
            widget: image
            required: false
          - label: Body
            name: body
            widget: markdown
            required: false
