export const baseSize: string;
export const headerFont: string;
export const bodyFont: string;
export const letterSpacing: string;
export const cardWidth: string;
export const chronology: string;
export const cardContainerWrapper: string;
export const cardContainer: string;
export const buffer: string;
