export const headerFont: string;
export const bodyFont: string;
export const letterSpacing: string;
export const cardWidth: string;
export const timeline: string;
export const areaGrabber: string;
export const isScrolling: string;
export const year: string;
export const tick: string;
