---
name: e2e-test
'on':
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node18.12.0-chrome107
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: pnpm run serve
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 900

      - name: Upload E2E screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 14

      - name: Upload E2E videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 14

      - name: Push changes to netlify if success
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.REPO_GITHUB_TOKEN }}
          branch: netlify
          force: true
