---
name: e2e-test
'on':
  push:
    branches:
      - master
    paths:
      - "!README.md"
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001 --shm-size=2g
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run serve
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 900

      - name: Upload E2E screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 14

      - name: Upload E2E videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 14

      - name: Push changes to netlify if success
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.REPO_GITHUB_TOKEN }}
          branch: netlify
          force: true
